### ISSUE TITLE
Where do animations go?

### ISSUE THREAD

**Issue by himynameisdave** [plum-css/plum#6]
Where do animations go? Like lets say I have some `@keyframes` animation to make something pulse, where would I put that?

The way that makes sense to me is to have like an `animations.scss` config file. Otherwise there will be animations in weird places like at the `unit` or `module` level when they in fact might want to be used across the site/page/app.

This might also be a good place to store common transitions, so what I like to do is:

``` scss
//  animations.scss
$short-transition: 0.175s cubic-bezier(.17,.67,.83,.67);

// ...elsewhere
.cool-class {
  transition: color $short-transition,
              background $short-transition,
              width $short-transition;
}

```
